spring:
    application:
        name: Sylfie
    config:
        import: optional:file:.env[.properties]
    security:
        user:
            name: a
            password: a
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
                        client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
                        scope:
                            - email
                            - profile
                    facebook:
                        client-id: your-facebook-client-id
                        client-secret: your-facebook-client-secret
                        scope:
                            - email
                            - public_profile
                provider:
                    facebook:
                        authorization-uri: https://www.facebook.com/v13.0/dialog/oauth
                        token-uri: https://graph.facebook.com/v13.0/oauth/access_token
                        user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
        cookie:
            remember-me: ${REMEMBER_ME_KEY}



    datasource:
        url: ${DATABASE_URL}
        username: ${AWS_USER}
        password: ${AWS_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

        show-sql: true

    messages:
        basename: messages

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 1000MB

server:
    address: 0.0.0.0
    port: 8080

cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY_ID}
            secret-key: ${AWS_SECRET_ACCESS_KEY}
        region:
            static: ${AWS_REGION}
        stack:
            auto: false
        s3:
            bucket: ${S3_BUCKET}
        default:
            avatar: ${AWS_DEFAULT_AVATAR_URL}