spring:
    application:
        name: Sylfie
    config:
        import: optional:file:.env[.properties]


    datasource:
        url: ${DATABASE_URL}
        username: ${AWS_USER}
        password: ${AWS_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

    messages:
        basename: messages

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 1000MB

server:
    address: 0.0.0.0
    port: 8080

cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY_ID}
            secret-key: ${AWS_SECRET_ACCESS_KEY}
        region:
            static: ${AWS_REGION}
        stack:
            auto: false
        s3:
            bucket: ${S3_BUCKET}