INSERT INTO tour_categories (id, name, description) VALUES
(1, 'Diving', 'Explore the underwater world in exotic locations.'),
(2, 'Hiking', 'Challenge yourself on scenic trails and rugged terrains.'),
(3, 'Safari', 'Experience wild nature and majestic animals up close.'),
(4, 'Cycling', 'Pedal through breathtaking landscapes and hidden paths.'),
(5, 'Cultural', 'Immerse yourself in rich history, food, and traditions.'),
(6, 'Skiing', 'Enjoy the thrill of snowy slopes and mountain resorts.'),
(7, 'Desert Trekking', 'Walk through vast deserts and sleep under the stars.'),
(8, 'Kayaking', 'Navigate lakes, rivers, and coastlines by kayak.'),
(9, 'Jungle Exploration', 'Venture deep into lush, mysterious rainforests.'),
(10, 'Volcano Tours', 'Visit and hike active and dormant volcanoes around the world.'),
(11, 'Northern Lights', 'Travel to the Arctic to witness the magical aurora borealis dancing across the sky.'),
(12, 'Island Hopping', 'Sail between breathtaking islands, discovering hidden beaches and local cultures.'),
(13, 'Dog Sledding', 'Ride through snowy landscapes with a team of enthusiastic huskies.'),
(14, 'Mountain Climbing', 'Summit iconic peaks with professional guides and breathtaking views.'),
(15, 'Glacier Tours', 'Walk atop ancient ice formations and enter shimmering blue caves.'),
(16, 'Nomadic Lifestyle', 'Live like a nomad: yurts, camels, and endless starry skies.'),
(17, 'Amazon River Cruise', 'Navigate the Amazon’s vast waterways and spot exotic wildlife.'),
(18, 'Jungle Trekking', 'Hike through remote rainforests filled with rare fauna and flora.'),
(19, 'Cave Exploration', 'Discover massive underground chambers and sparkling stalactites.'),
(20, 'Tundra Expeditions', 'Cross frozen plains in the far North, encountering reindeer and wild terrain.');

INSERT INTO location (id, city, country, latitude, longitude, name) VALUES
(1, 'Miami', 'USA', 25.7617, -80.1918, 'Miami'),
(2, 'Cusco', 'Peru', -13.5319, -71.9675, 'Cusco'),
(3, 'Cape Town', 'South Africa', -33.9249, 18.4241, 'Cape Town'),
(4, 'Interlaken', 'Switzerland', 46.6863, 7.8632, 'Interlaken'),
(5, 'Queenstown', 'New Zealand', -45.0312, 168.6626, 'Queenstown'),
(6, 'Marrakesh', 'Morocco', 31.6295, -7.9811, 'Marrakesh'),
(7, 'Banff', 'Canada', 51.1784, -115.5708, 'Banff'),
(8, 'Kyoto', 'Japan', 35.0116, 135.7681, 'Kyoto'),
(9, 'Ubud', 'Indonesia', -8.5069, 115.2625, 'Ubud'),
(10, 'Reykjavik', 'Iceland', 64.1466, -21.9426, 'Reykjavik'),
(11, 'Tromsø', 'Norway', 69.6496, 18.9560, 'Tromsø'),
(12, 'El Nido', 'Philippines', 11.1806, 119.3946, 'El Nido'),
(13, 'Longyearbyen', 'Svalbard', 78.2232, 15.6469, 'Longyearbyen'),
(14, 'Chamonix', 'France', 45.9237, 6.8694, 'Chamonix'),
(15, 'Vatnajökull', 'Iceland', 64.1667, -16.7833, 'Vatnajökull Glacier'),
(16, 'Ulaanbaatar', 'Mongolia', 47.8864, 106.9057, 'Ulaanbaatar'),
(17, 'Manaus', 'Brazil', -3.1190, -60.0217, 'Manaus'),
(18, 'Leticia', 'Colombia', -4.2153, -69.9406, 'Leticia'),
(19, 'Phong Nha', 'Vietnam', 17.5400, 106.2890, 'Phong Nha'),
(20, 'Murmansk', 'Russia', 68.9585, 33.0827, 'Murmansk');